os: linux
language: go
go:
- 1.15.1  # Bazel still uses its own version
env:
  global:
  - BAZEL_VERSION=3.4.1
  - BAZEL_SHA256=9808adad931ac652e8ff5022a74507c532250c2091d21d6aebc7064573669cc5
before_install:
- |
  wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  echo "${BAZEL_SHA256}  install.sh" | sha256sum -c
  chmod +x install.sh
install:
- |
  ./install.sh --user
  rm -f install.sh
script:
- travis_wait bazel build --config=ci //...
- go build
